### ISSUE TITLE
Scrapping en R

### ISSUE THREAD

**Issue by UrkoAlliBarrena** [VictoriaGarciaLovelle/PRACTICA_FUENTES_VICTORIA_URKO_PAULA#1]
Bueas Antonio,

Te comento en este issue para que como has dicho me puedas pasar un ejemplo de Srapping en R.

Un saludo.

**Comment by UrkoAlliBarrena** [comment]
@ajcanepa

**Comment by ajcanepa** [comment]
Hola @UrkoAlliBarrrena , @pgl1005 , @VictoriaGarciaLovelle .
Les he agregado algunos documentos y mejoras al repositorio, por lo que tendréis que hacer un `git pull` antes de hacer nada en vuestro repo.

Para el tema del pdf-scraping, os sugiero que cojáis los ejemplos mostrados [aquí](https://bookdown.org/Maxine/r4ds/pdf.html) y [aquí](https://www.brodrigues.co/blog/2018-06-10-scraping_pdfs/) y que vayáis __probando en paralelo__ los resultados del código entregado en los objetos que _ellos_ usan y __vuestros objetos__. 

Algo así he dejado en el script "`PDF_Scraping/Ejemplos/Ejemplo_web_pdf-scraping.R`" que está disponible en vuestro repositorio. No lo he desarrollado entero porque la idea es que lo hagáis paso a paso.

Si véis que se hace imposible, reemplazad vuestro fichero pdf (que tiene más de 100 páginas!) por solo aquella página que tiene la tabla con los datos que necesitáis.  Si hay más de una página, la podréis guardar como archivos independientes y seguir el procedimiento seguido [aquí](https://www.brodrigues.co/blog/2018-06-10-scraping_pdfs/).

Por el momento, es lo que os puedo ofrecer.

Suerte!

**Comment by pgl1005** [comment]
Hola Antonio, estoy teniendo algunos problemas a la hora de extraer unos datos específicos del archivo Json esperanzaVida.
He conseguido sacar algunos datos que nos interesan, como el nombre de la comunidad autónoma, la esperanza de vida y el año. Esos valores les he conseguido sacar de una dimensión que estaba dentro de otra dimensión y dentro de otra dimensión, etc... Pero hay un montón y no sé como puedo hacerlo con un bucle para que me saque todas las esperanzas de vida de andalucia en el año 2020 por ejemplo, ya que de andalucía hay muchos años y lo mismo con las demás comunidades autónomas.

Muchas gracias de antemano.
Un saludo.
